name: Deploy Angular Frontend to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version your app requires

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build --prod

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ssh ubuntu@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/frontend" # Create directory
            cd /var/www/frontend
            rm -rf * # Be careful!
            rsync -avz -e "ssh" ${{ github.workspace }}/dist/vamsi-store-frontend/ ubuntu@${{ secrets.EC2_HOST }}:/var/www/frontend  # Use rsync!
